### ISSUE TITLE
Is there a way to format the code so that it works in this vm

### ISSUE THREAD

**Issue by vin-fandemand** [ApolloVM/apollovm_dart#3]
I find it very difficult to just pass a string and make it run in the VM. Is there a formatter to format the text in such a way that it is acceptable by the VM?

**Comment by gmpassos** [comment]
Can you show some Code example? Thx

**Comment by vin-fandemand** [comment]
```
var codeUnit = CodeUnit(
        'dart',
        r'''
print('here');
      ''',
        'test');

    var loadOK = await vm.loadCodeUnit(codeUnit);

    if (!loadOK) {
      print("Can't load source!");
      return;
    }
```
This gives '"Can't load source!"

I want to know what is the criteria here for it to be good code.

**Comment by gmpassos** [comment]
See the example:
https://github.com/ApolloVM/apollovm_dart/blob/master/example/apollovm_example.dart

You need to encapsulate the code in an entry point (a function or a class).

**Comment by vin-fandemand** [comment]
```
    var codeUnit = CodeUnit(
        'dart',
        r'''
Map<String, dynamic> main(List<String> arg, List<dynamic> message) { return <String, dynamic>{'test' :1234};}
      ''',
        'test');

```
Why wouldn't this load ? It is encapsulated in a function and also runs okay in dartpad.dev

**Comment by gmpassos** [comment]
See https://github.com/ApolloVM/apollovm_dart/issues/4

**Comment by vin-fandemand** [comment]
Thanks. Can I import simple packages included in dart like convert, collection etc ?

**Comment by gmpassos** [comment]
Not yet, since this is only possible once a full Dart parser is implemented.

**Comment by gmpassos** [comment]
Please check the new version: `apollovm: ^0.0.35`

with support for `List` and `Map` literals.
